### Numpy Introduction with Basic Execution

##### Performance Benefits

In [4]:
import numpy as np
my_arr = np.arange(1000000)
my_arr_list = list(range(1000000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2 

CPU times: user 29.1 ms, sys: 16.7 ms, total: 45.9 ms
Wall time: 51.4 ms


In [6]:
%time for _ in range(10): my_arr_list2 = [x*2 for x in my_arr_list]

CPU times: user 553 ms, sys: 158 ms, total: 711 ms
Wall time: 731 ms


Numpy gives better performance (in between 10 times to 100 times) 

##### MultiDimensional Array Operation

In [11]:
### Initialization
k = np.zeros(shape = (2,5))
l = np.ones(shape = (3,4))
m = np.random.randn(1,2)
print(k)
print(l)
print(m)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[-1.42388485  1.09256028]]


In [12]:
# Scalar Multiplication
l * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [13]:
# Scalar addition
m + m

array([[-2.8477697 ,  2.18512057]])

##### Properties
- All element must be same type (Homogeneity) -> ndarray.dtype
- Shape can be viewed from -> ndarray.shape

In [14]:
print(m.shape)
print(l.dtype)

(1, 2)
float64


##### Creating N-Dim-Array from Any Sequence
- np.array(SequenceList)
    - Shape and Datatype will automatically inferred from List
    - ndarray.ndims -> Gives you number of dimension

In [16]:
l1 = [[1,2,3], [4,5,6]]

In [22]:
l_array = np.array(l1)

In [23]:
l_array

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
l_array.ndim

2

In [25]:
l_array.shape

(2, 3)

##### Other Operations

In [51]:
# Input conversion to NDArray
np.array([[1,2,3], [4,5,6]], dtype=np.float32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [30]:
# Input conversion to NDArray
np.asarray([[1,2,3], [4,5,6]]) # If Input is already ndarray then it doesn't copy

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
# Range Values as NDArray
np.arange(5, 20, 2) # np.arange(startVal, EndVal, Steps)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [35]:
# Array with all element is one
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
# Array with all element is one and shape as input array
np.ones_like([[1,2,3], [4,5,6]])

array([[1, 1, 1],
       [1, 1, 1]])

In [50]:
# Similar Operations
np.zeros((1,3)) # Zeros Elements
np.zeros_like([[1,2,3], [4,5,6]]) # Zeros Elements with Same Shape as input
np.empty((1,3)) # Empty array without initialization
np.empty_like([[1,2,3], [4,5,6]]) # Empty array with same shape as input without initialization
np.full((2,4),4) # Initialize array with given input
np.full_like([1,2,3,4,5], 3) # Initialize array with given input and same shape as input
np.eye(4) # Identity Matrix
np.identity(3) # Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### Type Casting
- ndarray.astype(dtype)

In [54]:
np.ones_like([[1,2,3], [4,5,6]]).astype(np.str)

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U21')

##### Arithmatic Operations

In [55]:
np_arr = np.array([[1,2,3],[4,5,6]])

In [56]:
# Addition
np_arr + np_arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [57]:
# Elementwise multiplication
np_arr * np_arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [58]:
# Scalar Division
1 / np_arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [59]:
# Scalar Multiplication
np_arr * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

#### Comparison

In [63]:
# Element Wise Comparison
z = np_arr * np_arr
print(z)
print(np_arr)

[[ 1  4  9]
 [16 25 36]]
[[1 2 3]
 [4 5 6]]


In [64]:
np_arr == z

array([[ True, False, False],
       [False, False, False]])

In [65]:
np_arr < z

array([[False,  True,  True],
       [ True,  True,  True]])

##### Slicing & Indexing
- Slice can be taken by index range same as list.
- Broadcasting with `:`

<font color='red'>Warning:</font> Changes in the slice variable will lead to change in original array.

In [79]:
arr = np.array([1,2,3,4,5])

In [80]:
slice_var = arr[2:4]
slice_var

array([3, 4])

In [81]:
slice_var[0] = 6
slice_var

array([6, 4])

In [82]:
arr

array([1, 2, 6, 4, 5])

In [83]:
# Broadcasting
arr[2:4] = 3

In [84]:
arr

array([1, 2, 3, 3, 5])